2024-10-07 19:42:23,798 INFO    MainThread:151139 [wandb_setup.py:_flush():79] Current SDK version is 0.18.3
2024-10-07 19:42:23,798 INFO    MainThread:151139 [wandb_setup.py:_flush():79] Configure stats pid to 151139
2024-10-07 19:42:23,798 INFO    MainThread:151139 [wandb_setup.py:_flush():79] Loading settings from /home/enzo/.config/wandb/settings
2024-10-07 19:42:23,798 INFO    MainThread:151139 [wandb_setup.py:_flush():79] Loading settings from /home/enzo/Documents/gpt2/wandb/settings
2024-10-07 19:42:23,798 INFO    MainThread:151139 [wandb_setup.py:_flush():79] Loading settings from environment variables: {}
2024-10-07 19:42:23,798 INFO    MainThread:151139 [wandb_setup.py:_flush():79] Applying setup settings: {'mode': None, '_disable_service': None}
2024-10-07 19:42:23,798 INFO    MainThread:151139 [wandb_setup.py:_flush():79] Inferring run settings from compute environment: {'program_relpath': 'gpt2_fabric.py', 'program_abspath': '/home/enzo/Documents/gpt2/gpt2_fabric.py', 'program': '/home/enzo/Documents/gpt2/gpt2_fabric.py'}
2024-10-07 19:42:23,798 INFO    MainThread:151139 [wandb_setup.py:_flush():79] Applying login settings: {}
2024-10-07 19:42:23,798 INFO    MainThread:151139 [wandb_init.py:_log_setup():532] Logging user logs to ./wandb/run-20241007_194223-z3h9pnta/logs/debug.log
2024-10-07 19:42:23,799 INFO    MainThread:151139 [wandb_init.py:_log_setup():533] Logging internal logs to ./wandb/run-20241007_194223-z3h9pnta/logs/debug-internal.log
2024-10-07 19:42:23,799 INFO    MainThread:151139 [wandb_init.py:init():617] calling init triggers
2024-10-07 19:42:23,799 INFO    MainThread:151139 [wandb_init.py:init():624] wandb.init called with sweep_config: {}
config: {}
2024-10-07 19:42:23,799 INFO    MainThread:151139 [wandb_init.py:init():667] starting backend
2024-10-07 19:42:23,799 INFO    MainThread:151139 [wandb_init.py:init():671] sending inform_init request
2024-10-07 19:42:23,801 INFO    MainThread:151139 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-10-07 19:42:23,801 INFO    MainThread:151139 [wandb_init.py:init():684] backend started and connected
2024-10-07 19:42:23,805 INFO    MainThread:151139 [wandb_init.py:init():779] updated telemetry
2024-10-07 19:42:23,807 INFO    MainThread:151139 [wandb_init.py:init():812] communicating run to backend with 90.0 second timeout
2024-10-07 19:42:24,512 ERROR   MainThread:151139 [wandb_init.py:init():838] encountered error: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-10-07 19:42:24,512 ERROR   MainThread:151139 [wandb_init.py:init():1262] error in wandb.init()
Traceback (most recent call last):
  File "/home/enzo/mambaforge/envs/up_to_date/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 1252, in init
    return wi.init()
           ^^^^^^^^^
  File "/home/enzo/mambaforge/envs/up_to_date/lib/python3.12/site-packages/wandb/sdk/wandb_init.py", line 844, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2024-10-07 19:42:24,769 WARNING MsgRouterThr:151139 [router.py:message_loop():77] message_loop has been closed
